
s1 = "AAAACCCGGT"
s1[::-1]
s1[::2]

def complementaryDNA(string):
    rev = string[::-1]
    stringOut = ''
    for nucleotide in rev:
        if nucleotide == 'A':
            stringOut += 'T'
            continue
        if nucleotide == 'C':
            stringOut += 'G'
            continue
        if nucleotide == 'G':
            stringOut += 'C'
            continue
        if nucleotide == 'T':
            stringOut += 'A'
            continue
    return(stringOut)

print(complementaryDNA(s1))
            

s2 = "AGTGCACGGTATTTATCTCAACGTTATAAGTCGGCGGCATAGAGGTTGAGCACACGTCGGCCGGTCGTTACCCCCAGAACACCACGCAACCGAGCGTTCATTCGCACGCCCAGTTTTTTAAAACGTCCCAGTGCGCCCGAAGCTGTTTTCTATTAGAGATGCCGGTCCGTGCGTAATGGCGGTTATATATAATGTTGAGAGTGACGACATTTGCGCTCCCGTCGAACTCTCTAGAATTCCGAGTCGCCCGTCGTACATTGCATGGAGTTGCTAAGTGCCTTGAAACACGACGTCTTCGAGCCGAGCACGTGATCCAACTCAATGAGAGTATCAGCAGTAGCACGCTAGTATGCCAGAAGTGTCACCCTAAGGCGTGTACACATGTGGGCGGAGTAAGGCGTTGATGCTCCCCTTTCATTTCGGACGACACGCCTCTGCTTTTCTCAAGACGAATTATGTGAAAGGAAGGCGCTACATGTGTATAGCTCGGACGAATGCTACGGAAATATGGTAGCCTGAAGGGAGCTTGAGCTCAGACAGAACCGCGCCACAAAGAGGGACCGGACTCGTCAAGGCCGAGGGGCTTACTTCATCACTGGCAAACATGGCAGGCCTTTACAGCGTAGCCCATGTACATTTACATGTCCTGTGGATGCTGGGCAGATTCGCAATGGAGTTTACGCTTATAGACAGGAGATCATATAGACTGACACGTTGATATCCTGCCAAGCCGTTTGGTTCATGCGACACGTCCAGGAAGTGAAAGCTACCGAATCTGTATATCATTCTAGTCACTGCGAACCATGGGGCAGACTACCTGTAATCAAC"

print(complementaryDNA(s2))