# Split string up into individual chars, then count # of each char in the dict. 

# e.g.  AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

s = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"

splitString = [*s] # this is called `unpacking` ... there are many other ways to separate out characters of a string. several use for loops. 
print(splitString)

def countNucleotides(string):
    ssplit = [*string]
    letterCounter = {}
    for letter in ssplit:
        if letter in letterCounter:
            letterCounter[letter] = letterCounter[letter] + 1
        else:
            letterCounter[letter] = 1
    return(str(letterCounter.get('A'))+ " " +str(letterCounter.get('C'))+ " " +str(letterCounter.get('G'))+ " " +str(letterCounter.get('T')))

print(countNucleotides(s)) # this passes the check!

s2 = "ACTAGTTAAGCCGTCAATATTCCATTTTTAATAGCAGTTAATGGTTAAGTCGTGCAAACCTCCTTTTTCCAAAATTGCGATCATTGGAGAAGCTAAGCTTAATTGTACGTAAGTAACGCAGGAGTGTGGGCACTTACATAAACCTCGGTTGTCCATGTGTTAACCTGTGTTGCAGCATTTTATAAGCATTTGTCTGCGAGAAGGAATGGATCTCATTTGCGCGTCCTCCGACTGAGCATCTATCTAAATCCGGCGCCTTCTACCGAGTATATGTACACCCGCCAACCTTCCACTAGGAGATCTGAGCGGCCTGCCAAGCAACATGATATCCGCATAATGACTCTTGAAGGGTACTATTCCTTAGTGCTAAGCCGGGTGGCACCACGGTACGTCGCAATGAAGTCTTGAGCGTAGTCCGCAAGGCGAGTCGTTTCGACGTCTCGTGTTGCGTTACGCTCATGTAACTGAATAAGTAGGACTTCTCGGCATGCTGCCACGGACCGTGACTGTCGTGATCCCGGGATCTTTTCCGAGCGGCAGCTCCCAAATGCAAACATTGTAAACATGGCCACCAAGCTCATCCGTTCCTGCTCGCCGGCGCCCGCGTCGAAACCGCGGCTAGGAGAGCGGACATTCCTTCCCAGAAAAGTTGTGATAAACATTCTATGCCAATCTATACGGAGCCTCTTTTTGCCTATATATACACAAGATTATGCATTCCACCGCTGAGCCCCATATAGGAGTTATTCATGGCATTCATGAACTATTTGTAGGTATCACGTTGCAAAAGCTACTTCAGGATCGCTGATTAAGTGCCGACATAAACACGGCTGCGG"

print(countNucleotides(s2))